### ISSUE TITLE
Site is completely broken after deployment

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [emilyseville7cfg-better-emacs/site.github.io#11]
Look [this](https://www.reddit.com/r/Jekyll/comments/100ga84/why_my_site_is_broken_after_deployment/) for details. I don't know how to fix this issue...

**Comment by kbdharun** [comment]
Does this theme support GitHub pages?

**Comment by EmilyGraceSeville7cf** [comment]
It should be supported by them, it's the default one.

**Comment by kbdharun** [comment]
> It should be supported by them, it's the default one.

I will check it out closely later tomorrow.
